### PR TITLE
FEATURE: Add course description to course details page

### LINKED ISSUE #6: FEATURE: Add course description to course details page
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

User

### I can...

View a course's details

### So that...

I can know the course description

### Discussion

On the course details page, currently we only see information that is available from the course search: lecture days, times, professor, location, enrollment, etc. I would like to be able to view the course description from this page, so that I don't have to leave this search page to use the "Course Descriptions" search.

Something like this (obviously nicer-looking than this):
Your paragraph text

### Acceptance Criteria

- [x] On a course details page, there should be a text box containing the course description
- [x] This should access the course description returned from the backend's basic search (same as the Course Descriptions search)

### Implementation Todos

Frontend:
- [x] Add a component which takes a course and displays the course description
- [x] Add this component to the CourseDetailsIndexPage
- [x] Add an API call to the CourseDetailsIndexPage which calls the same API as the Course Descriptions search to get the course description

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by samanthwest**
added course description to the course details page so that you dont have to access it on another page

Before:
Screenshot 2024-02-28 at 10 05 24 PM

After:
Screenshot 2024-02-28 at 10 02 55 PM

Dokku dev:
https://project-samanthwest.dokku-08.cs.ucsb.edu

Closes #6

### CODE REVIEW

**Review by megumi-ondo — CHANGES_REQUESTED** [review]
Looks good, after dokku link is added + it works, will approve.

**Review by megumi-ondo — DISMISSED** [review]
LGTM

**Comment by samanthwest** [comment]
@tallyhawley @AnikaArora this pull request has been peer reviewed if you guys could review it whenever you get the chance! thank you :)

**Review by tallyhawley — DISMISSED** [review]
Looks good to me :) :shipit:

**Review by tallyhawley — CHANGES_REQUESTED** [review]
Could you add some tests please!

**Pull request closed without merging**
