### PR TITLE
BUG: Personal Schedules Update not updating the Quarter field

### LINKED ISSUE #21: BUG: Personal Schedules Update not updating the Quarter field
Description of the bug:
Because the quarter field was a dropdown, code from other projects/assignments that was copied over did not update the quarter field correctly. 

How to replicate:
Copy over edit page code from team03. Change names and parameters as expected. You will notice that once you test, the quarter field cannot is not edited. 

Acceptance Criteria:
Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by Cory-Zhao**
Fixed the bug where the edit page doesn't update the quarter field. Bug was in the onSubmit function inside PersonalSchedulesEditPage.js where I added code that updates quarter field. Tests pass 

https://proj-courses-cory-zhao-dev.dokku-08.cs.ucsb.edu/

Closes #21

### CODE REVIEW

**Comment by tallyhawley** [comment]
Please set up HTTPS so I can access your app on dokku

**Comment by Cory-Zhao** [comment]
> Please set up HTTPS so I can access your app on dokku

Fixed

**Review by ColeFoster08 — DISMISSED** [review]
LGTM

**Comment by Cory-Zhao** [comment]
> Please set up HTTPS so I can access your app on dokku

Can you clarify how many points this bug will be. Our team needs to know for the total tally.

**Comment by tallyhawley** [comment]
Looking at the code, this looks like it was a bug in your own implementation of the EditPage in #18 . I can't really give you bonus points for fixing your own code, since it hasn't even been merged yet.

**Pull request closed without merging**
