### PR TITLE
FEATURE: More descriptive error message on personal schedule

### LINKED ISSUE #5: FEATURE: More descriptive error message on personal schedule
### Have you updated the title?

- [ ] I have updated the issue's title.

### As a...

user

### I can...

get a better error message when adding a course with no schedule

### So that...

I can understand why it's not working

### Discussion

Currently, adding a course with no personal schedule available just returns the text "Error.". Please replace this with a more descriptive error message so that the user knows that they have to create a personal schedule first.

OPTIONAL BONUS: If this happens, give the user a way to create a new schedule without having to find the page themselves -- either link to the "Create Schedule" page or create a modal/pop-up to quickly create a schedule without leaving the page (worth more points).

### Acceptance Criteria

- [x] Trying to add a course to a schedule with no schedule created should return a more descriptive error message which describes the actual issue
- [x] [BONUS] The user can easily create a new schedule if this error is found.

### Implementation Todos

Frontend:
- [x] Replace the "Error" message with a more descriptive error message.
- [x] [BONUS] Add a link to the create schedule page OR a modal / pop up to quickly create a schedule.

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by Torry051**
Add a more descriptive error message. When user want to add a course without any schedule, it will report error.

For bonus part, I add a button to create a new personal schedule. This button will only show up, when the page report error.

Error

Dokku dev:
https://project-samanthwest.dokku-08.cs.ucsb.edu

Closes #5

### CODE REVIEW

**Comment by tallyhawley** [comment]
Please add the issue that this PR closes to the description, as well as a dokku link if you can :)

**Review by samanthwest — DISMISSED** [review]
LGTM!

**Review by tallyhawley — CHANGES_REQUESTED** [review]
This is not expected behavior:

image

It should still return the original error message if there is a personal schedule present.

**Comment by Torry051** [comment]
image

The original error message will show when there is personal schedule.

**Review by megumi-ondo — DISMISSED** [review]
LGTM!

**Comment by tallyhawley** [comment]
> The original error message will show when there is personal schedule.

Has this been deployed to dokku? Testing on dokku right now, I still see the old behavior:
image

**Comment by Torry051** [comment]
> > The original error message will show when there is personal schedule.
> 
> Has this been deployed to dokku? Testing on dokku right now, I still see the old behavior: image

https://proj-courses-torry051-dev.dokku-08.cs.ucsb.edu

Sorry, I forgot to update the deployment. Here is the new deployment.

**Comment by tallyhawley** [comment]
Running into another issue: probably the same as https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/issues/20

image

Got around that issue and got this (400 errors on dokku do not have a message, but they do on localhost):
image

**Review by samanthwest — DISMISSED** [review]
LGTM

**Comment by tallyhawley** [comment]
Has your dokku been redeployed? I'm still seeing the same behavior as before.

**Comment by Torry051** [comment]
> Has your dokku been redeployed? I'm still seeing the same behavior as before.

It should work now
 https://proj-courses-torry051-dev.dokku-08.cs.ucsb.edu

**Comment by tallyhawley** [comment]
Still getting the same behavior.

https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-4/assets/20908336/8e485539-600e-46dc-8f14-aca0cad9d56d

**Pull request closed without merging**
