### PR TITLE
BUG: Can't immediately search for graduate courses

### LINKED ISSUE #13: BUG: Can't immediately search for graduate courses
### Have you updated the title?

- [X] I have updated the issue's title.

### Summary

When searching for graduate courses, the first search shows both undergraduate & graduate courses. It filters correctly if you re-do the search, but resets to undergrad+grad if you search after refreshing the page.

### Expected Behavior

I should be able to view graduate-only courses on my first try.

### Current / Observed Behavior

When I first attempt to view graduate-only courses, the search returns undergraduate courses as well.

### Steps to Reproduce

1. Navigate to courses.dokku-00.cs.ucsb.edu
2. Set the course level to "Graduate"
3. Press "Search"

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by ColeFoster08**
Changed files:
- frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
- frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
- frontend/src/tests/components/Levels/SingleLevelDropdown.test.js

This pull request addresses the bug that wouldn't allow the user to search for graduate courses on the first search.

The issue was caused by the controlId for the course level being set wrong in BasicCourseSearchForm. This meant that whenever the page was loaded, the value that was shown in the CourseLevel drop-down box was not the level being searched. However if the user interacted with the drop-down menu to change this value, SingleLevelDropdown would take over and set the right value in the search. (This is what allowed the table to be right on the second search)
So the bug wasn't only for graduate courses but would affect any course level when the page was reloaded and submitted with a course level not previously submitted.

One way to reproduce this bug:
- Set the course level to something other than already shown in the box (I choose Undergrad-Lower-Division)
  - (This will update the value being used through SingleLevelDropdown, so everything should be set correctly)
- Press submit
  - (This should give the correct table for that course level)
- Change the level field to any other value and without submitting, refresh the page (I choose Graduate)
- Finally submit, the bug should cause the table to populate with values that aren't from the selected course level
  - (In my case this was the table for Undergrad-Upper-Division)
- To test that the second search works, change the course level to a random value and then change it back to Graduate
  - (It should now have the right table for Graduate courses)
  
Screenshot 2024-02-29 at 10 25 13 PM

After changing BasicCourseSearchForm, the search page now recognizes the value in the drop-down menu without the need to change it to update the value being searched. You can test this fix with the same steps as above, although this time the table generated should be correct all the time.

To help test this fix, in the code I added tests in BasicCourseSearchForm.test to make sure that the page loads with values for the conrolId: CourseLevel (along with confirming the other controlId names are set correctly).
I also changed tests in SingleLevelDropdown.test to test course level values other than the default ("U")

Test initial bug at: https://courses.dokku-00.cs.ucsb.edu/
Dokku site at: https://proj-colefoster08-dev.dokku-08.cs.ucsb.edu

Closes: #13

### CODE REVIEW

**Review by Cory-Zhao — DISMISSED** [review]
LGTM

**Comment by ColeFoster08** [comment]
@tallyhawley could you review this pull request?

**Review by tallyhawley — APPROVED** [review]
Looks good to me :)

**Review by Cory-Zhao — APPROVED** [review]
LGTM

**Comment by ColeFoster08** [comment]
@tallyhawley This pull request has 2 approvals, can it be merged to main?

**Comment by ColeFoster08** [comment]
@tallyhawley this pull request has 2 approvals and is up-to-date with main, can it be merged?

**Pull request merged**
